/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Models.ITRequest;
import Repository.ITRepository;

import javax.swing.*;
import java.sql.Date;
import java.sql.SQLException;

/**
 *
 * @author Acer
 */
public class DemoForm extends javax.swing.JFrame {

    /**
     * Creates new form DemoForm
     */
    public DemoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jReqId = new javax.swing.JLabel();
        jReqDate = new javax.swing.JLabel();
        jReqType = new javax.swing.JLabel();
        jReqName2 = new javax.swing.JLabel();
        jReqDetails = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jTextDate = new javax.swing.JTextField();
        jTextType = new javax.swing.JTextField();
        jTextDetails = new javax.swing.JTextField();
        jTextName = new javax.swing.JTextField();
        jAddBtn = new javax.swing.JButton();
        jFindBtn = new javax.swing.JButton();
        jClearBtn = new javax.swing.JButton();
        jReqEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("IT Request");

        jReqId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReqId.setText("ReqID");

        jReqDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReqDate.setText("ReqDate");

        jReqType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReqType.setText("ReqType");

        jReqName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReqName2.setText("ReqName");

        jReqDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReqDetails.setText("ReqDetails");

        jTextId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTypeActionPerformed(evt);
            }
        });

        jTextDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDetailsActionPerformed(evt);
            }
        });

        jTextName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jAddBtn.setText("Thêm");
        jAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBtnActionPerformed(evt);
            }
        });

        jFindBtn.setText("Tìm");
        jFindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFindBtnActionPerformed(evt);
            }
        });

        jClearBtn.setText("Xóa");
        jClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBtnActionPerformed(evt);
            }
        });

        jReqEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jReqEmail.setText("ReqDate");

        jTextEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jAddBtn)
                        .addGap(73, 73, 73)
                        .addComponent(jFindBtn)
                        .addGap(73, 73, 73)
                        .addComponent(jClearBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jReqType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jReqDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextType, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jReqName2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jReqId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jReqDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jReqEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReqId)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReqName2)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReqDate)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReqEmail))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReqType)
                    .addComponent(jTextType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReqDetails)
                    .addComponent(jTextDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddBtn)
                    .addComponent(jFindBtn)
                    .addComponent(jClearBtn))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTypeActionPerformed

    private void jTextDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDetailsActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jFindBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        ITRepository repo= new ITRepository();
        ITRequest request = new ITRequest();
        try{
           request = repo.findById(jTextId.getText());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Tìm thất bại!");
        }
        String reqid = String.valueOf(request.getReqId());
        jTextId.setText(reqid);
        jTextName.setText(request.getReqName());
        jTextDate.setText(String.valueOf(request.getReqDate()));
        jTextEmail.setText(request.getReqEmail());
        jTextType.setText(request.getReqType());
        jTextDetails.setText(request.getReqDetails());
    }

    private void jClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBtnActionPerformed
        jTextId.setText(null);
        jTextName.setText(null);
        jTextDate.setText(null);
        jTextEmail.setText(null);
        jTextType.setText(null);
        jTextDetails.setText(null);
    }//GEN-LAST:event_jClearBtnActionPerformed

    private void jAddBtnActionPerformed(java.awt.event.ActionEvent evt) {
        ITRepository repo = new ITRepository();
        try{
            repo.addRequest(jTextName.getText(),jTextDate.getText(),jTextEmail.getText(),jTextType.getText(),jTextDetails.getText());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Thêm request thất bại rồi!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddBtn;
    private javax.swing.JButton jClearBtn;
    private javax.swing.JButton jFindBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jReqDate;
    private javax.swing.JLabel jReqDetails;
    private javax.swing.JLabel jReqEmail;
    private javax.swing.JLabel jReqId;
    private javax.swing.JLabel jReqName2;
    private javax.swing.JLabel jReqType;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextDetails;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextType;
    // End of variables declaration//GEN-END:variables
}
